name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Debug Info
      run: |
        echo "Current directory: $(pwd)"
        ls -al

    - name: Build and publish the API
      run: |
        dotnet publish -c Release -o ./publish
      working-directory: /home/runner/work/hexalambda/hexalambda

    - name: Zip Files
      run: |
        cd ./publish
        zip -r mylambda.zip *
      working-directory: /home/runner/work/hexalambda/hexalambda

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code --function-name hexalambda --zip-file fileb://./publish/mylambda.zip
        aws lambda update-function-configuration --function-name hexalambda --environment "Variables={YOUR_ENV_VARIABLES}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
